### ISSUE TITLE
reproducible files

### ISSUE THREAD

**Issue by fekir** [OptiVorbis/OptiVorbis#41] opened 2023-08-10 15:07 UTC
`optivorbis` compares itself to jpegoptim and optipng, but it has one big difference: it seems to always generate a different file.

````
optivorbis file1.ogg file2.ogg
optivorbis file2.ogg file3.ogg
optivorbis file1.ogg file4.ogg

md5sum file2.ogg file3.ogg file4.ogg
````

All hashes are different (all sizes are equal).

`jpegoptim` and `optipng` detect if the file they are overwriting would have a bigger or equal size, and do not overwrite it.

It would be nice if `optivorbis` would create reproducible files (as in: same input, same output).

**Comment by AlexTMjugador** [comment] 2023-08-10 17:39
Hi, thanks for reaching out! :smile:

By default, OptiVorbis strives to adhere closely to the [Ogg format specification](https://www.xiph.org/ogg/doc/rfc3533.txt). Section 4 of that specification states that every Ogg stream is composed of logical bitstreams with an identifying serial number, and "this unique serial number is created randomly". Therefore, it is expected that OptiVorbis will generate slightly different files for the same input by default, since the logical bitstreams they contain should have different serial numbers.

However, if reproducibility of the generated files is your uttermost concern, you can opt out of randomizing stream serials by using the already available `randomize_stream_serials` remuxer option, like this: `optivorbis --remuxer_option randomize_stream_serials=false file1.ogg file2.ogg` (see also the related `first_stream_serial_offset` option). After doing this, the generated files for the same input and options should always be byte-identical (i.e., have the same hashes).

Please note that randomly generating stream serials is **not** just a pedantic requirement of the Ogg specification: doing so makes it possible to easily create valid, chained Ogg streams by `cat`ting them together, which would not be possible if serial numbers were shared across files. ([Source](https://linux.die.net/man/1/oggz-merge).)

If you want to verify that OptiVorbis has indeed generated equivalent audio files for the same inputs without giving up on random serial number generation, I suggest comparing the decoded audio samples and other file metadata instead. You can do this by comparing the output of the `ogginfo` and `oggdec` command-line tools for the generated files.

I'm closing this as I believe the feature you requested is already available and this comment provided the necessary context to use it properly, but please feel free to get in touch if you have anything else to add.

**Comment by fekir** [comment] 2023-08-10 20:47
Thank you for the fast reply.

I'm interested in a reproducible output as part of a bigger project (https://reproducible-builds.org/), comparing the files and metadata is something I would absolutely want to avoid.


> Section 4 of that specification states that every Ogg stream is composed of logical bitstreams with an identifying serial number, and "this unique serial number is created randomly".

Yes, I have no idea how an ogg file is structured, but by doing a diff I can see that the differences are minimal. With diffoscope it is possible to see that only serial no. and checksum differs.

And I can also confirm that the option works as you've described.


> doing so makes it possible to easily create valid, chained Ogg streams by catting them together

Does it mean that catting a file to itself is not supported?


Either way, since the input file and the output file are platonically the same audio file, wouldn't it make sense to reuse the same id? Would be there any disadvantages?

**Comment by AlexTMjugador** [comment] 2023-08-11 11:40
I'm glad to hear that the option worked well for you!

> Does it mean that catting a file to itself is not supported?

Yes, that's correct. Chaining an Ogg file to itself with `cat` will not work, because it would create an invalid physical Ogg bitstream, with at least two logical bitstreams having the same serial number. Decoders strictly require that the serial numbers within a file are different: otherwise they can't properly parse and seek each bitstream.

> Either way, since the input file and the output file are platonically the same audio file, wouldn't it make sense to reuse the same ids? Would be there any disadvantages?

The Ogg specification says that a bitstream serial number "does not have any connection to the content or encoder of the logical bitstream it represents". My interpretation of that sentence is that serial numbers should always be randomly generated, as otherwise there would be a "connection" between the content of the logical bitstream and its serial number.

On the practical side, the default behavior of generating random serial numbers allows `cat`ting a file to an equivalent version of itself, and also enables `cat`ting of files that share stream serial numbers, where such numbers were only unique within their own files. Passing through serial numbers would not guarantee these properties, which I think are nice to have by default.

However, it can be argued that `cat`ting (i.e., chaining) Ogg files is a very niche use case. Frankly, I didn't know about it until I did the necessary Ogg format research to develop OptiVorbis, and hardly anyone on the Internet mentions it as an advantage of the Ogg Vorbis format. The fact that two different files share bitstream serials does not matter for decoding: after all, decoders have to work with each file independently, [the possibility of serial number collisions between files is not zero](https://en.wikipedia.org/wiki/Birthday_problem), and that serial numbers are generated ["randomly" is hard to test for](https://i.imgur.com/bwFWMqQ.png). So, if your users will never chain Ogg files, not randomizing serial generation can be the right call. Besides the chaining use case, I'm not aware of any other drawbacks to not randomizing serials.

Given these considerations, I don't think I will introduce functionality to copy stream serial numbers in OptiVorbis, but you are welcome to disable their randomization if that fits your use case better. If you are inclined to copy stream serials anyway, you might want to fetch the original serial with `ogginfo`, and then use the `randomize_stream_serials` and `first_stream_serial_offset` options to tell OptiVorbis to use that serial for the bitstream it will generate. Alternatively, you can use the [`rogg_serial`](https://gitlab.xiph.org/xiph/rogg) tool, which is part of the `rogg` suite of tools mentioned in the OptiVorbis README.

**Comment by fekir** [comment] 2023-08-11 12:28
Than you for the detailed explanation.

> However, it can be argued that catting (i.e., chaining) Ogg files is a very niche use case. [...] and hardly anyone on the Internet mentions it as an advantage of the Ogg Vorbis format. 
Yeah, I'm not interested in catting ogg files together, especially now, knowing that `cat` might create an invalid file depending on the input, and the user has no control/feedback.
I suppose there are better tools for concatenating audio files together.

> The Ogg specification says that a bitstream serial number "does not have any connection to the content or encoder of the logical bitstream it represents". My interpretation of that sentence is that serial numbers should always be randomly generated, as otherwise there would be a "connection" between the content of the logical bitstream and its serial number.

Mhm, OK, I hoped it would have be a way to have a good compromise: non-random ids, and different ids for file that had different ids before the optimization.


It seems to me you would prefer to creating random id by default, and non-random explicitly (the status quo).

Obviously I would prefer it to be the other way round XD

Would it at least be possible to support the environment variable `SOURCE_DATE_EPOCH` (see https://reproducible-builds.org/docs/source-date-epoch/)?

Yes, I can set the flag `--remuxer_option randomize_stream_serials=false`, or define a shell alias.

The main advantage of `SOURCE_DATE_EPOCH` is that it is a standardized environment variable; a single API for controlling multiple tools (compiler, archiving tools, ...).

Being an environment variable, it works "well" when I'm not invoking `optivorbis` directly; for example if it used internally by some other tool.

**Comment by fekir** [comment] 2023-08-11 19:46
> [...] tools such as Audacity, GStreamer or ffmpeg, no audio data is re-encoded

Just thinking out loud; I think with `ffmpeg` it is possibly to concatenate without transcoding/reencodign the audiostream, but maybe only in some situation (like equal sample rate)?

> what do you think

Well, I would still prefer not have to defined the variable (it was a surprise for me that different runs on the same input generate different outputs, just lucky me that I decided to check), but it sounds good.


> the same files optimized in the same OptiVorbis run (which is currently only possible via the Rust API, not the CLI) would still get different serials

I do not think I've understand that part, unless you meant "different" instead of "same".

**Comment by AlexTMjugador** [comment] 2023-08-11 20:16
> Just thinking out loud; I think with `ffmpeg` it is possibly to concatenate without transcoding/reencodign the audiostream, but maybe only in some situation (like equal sample rate)?

[It may be possible](https://trac.ffmpeg.org/wiki/Concatenate), but I couldn't get FFmpeg to output an Ogg Vorbis file with two logical bitstreams, as `cat` would do. It looks like the lossless concatenation features offered by FFmpeg insist on outputting a single logical bitstream, which, unlike the `cat`ting approach, can only work well if two Ogg Vorbis files share exactly the same codec parameters (number of audio channels, sampling frequency, and codec setup data that OptiVorbis adapts to each file to achieve more efficient encoding).

> I do not think I've understand that part

I was just thinking out loud how that idea would prevent repeating serials under most circumstances, don't worry about the specifics! I'm happy to read that the environment variable is an acceptable solution for you, and I'm also happy to not make things harder for any folks out there who might use Ogg stream chaining by default :wink:

I'm reopening this issue to better track progress on the related reproducible builds standard.

**Comment by AlexTMjugador** [comment] 2023-08-23 21:55
Hey @fekir, I've just implemented support for the `SOURCE_DATE_EPOCH` environment variable! :tada:

Please feel free to look at the corresponding commit above and give feedback on the changes. There hasn't been a release with these changes yet, so you'll need to get OptiVorbis executables from CI (which is currently broken due to a regression in rustdoc that should be fixed soon) or by building from source.

I'll close this issue as soon as I receive positive feedback about the new feature or I decide to release it, whichever happens sooner.

**Comment by fekir** [comment] 2023-08-24 14:50
Thank you for looking at it.

I did not test it (I do not have the possibility to build it right now), but the changes you made makes at least sense :)

**Comment by AlexTMjugador** [comment] 2023-12-11 23:42
After some other QoL changes, OptiVorbis v0.2.0 has been released with this feature! :tada:

Sorry it took me so long to make a release. I hope it was at least worth the wait :slightly_smiling_face:

**Closed by AlexTMjugador** 2023-12-11 23:42 UTC
Labels: enhancement
